== The Events API

The Events API is defined in various header file (eventhandler.h, gpio_events.h
& timer_events.h)

---
=== Event Handler

typedef void(*gpio_action_t) (uint gpio, uint32_t events) :: The GPIO event
processing function prototype.

void onEventGPIO(gpio_action_t action,uint32_t mask) :: Define the GPIO event
processing function for a particular member of a set of IRQ sources.

void insert_gpio_event(uint gpio, uint32_t event) :: Insert a GPOI event into
the event queue - for a particular pin and interrupt.

typedef void(*timer_action_t) (uint32_t timerindex) :: The timer event
processing function prototype.

void onEventTimer(timer_action_t action) :: Define the timer event
processing function.

void insert_timer_event(uint32_t *timerindex) :: Insert a timer event into
the event queue.

void eventHandler() :: Execute the event handler.

---
=== GPIO Events

bool gpio_debounce_enable_events(uint from_pins[], uint to_pins[], uint count, uint32_t eventmask) ::
Enable the GPIO debounce processor (PIO program) using a set of pins (from_pins), set the inverted
version of the ddebounced signals on another set of GPIO pins and enable GPIO events from these debounced
pins when any one of a defined set of IRQ states occur.

bool gpio_enable_events(uint pins[], uint count, uint32_t eventmask) ::
Enable GPIO events from a set of pins when any one of a defined set of IRQ states occur.

---
=== Timer Events

bool timer_enable_events(int32_t delay_ms) :: Enable Timer events every _delay_ms_ milliseconds.
