= NBPCG User Guide - Release Notes
Richard Linsdale
2022-05-21
:jbake-type: document
:jbake-status: published
:jbake-previouspage: developer
:jbake-sectionlistname: nbpcg_ug
~~~~~~

== Release Notes

=== Release 5.0.1

Updated build process relating to auto update.

=== Release 5.0.0

Updated to work with Netbeans 8.2;
Major update to the release process to use Maven Central for delivery;
Documenation now delivered via GitHub-Pages

=== Release 4.0.26

Updated to work with NetBeans 8.1; Revisions to internal implementation of forms.

=== Release 4.0.20

Added creation of separate entity source classes and any required table classes (for use with node editors).

=== Release 4.0.15

Build Process Update - uses latest(V2) POMs. No user or functional changes.

=== Release 4.0.14

Major update/refactoring of NBPCG generated code (and its associated libraries: nbpcg-library 3.1.7 and lindos 3.1.7).
Includes explicit generation of additional fields (timestamps, ids and indexes), restructuring of the data access to utilise new APIs and other 
changes to templates and XSLT generated definintions

