== The ActionsSupport API

=== NodeDynamicActions

NodeDynamicActions creates DynamicCLIActions for a  node, using a
properties file to define the actions.

NodeDynamicActions observes the node folder containing the properties file,
ensuring the actions are updated whenever changes to the properties file occur.

Additional files within the node folder can be observed,
so that changes can trigger updates to any associated objects.

NodeDynamicActions provides a method for assembling node actions, combining
various sources of actions to create the final dynamic actions array required by
a node definition.


public static enum FileChangeType {CREATED, CHANGED, RENAMEDTO, RENAMEDFROM, DELETED} ::
The types of file changes which are observed by NodeDynamicActions.
    

==== Constructor

public DynamicActions(FileObject filefolder, String actionpropertiesfilename) ::
Create a DynamicActions object:
* _filefolder_ The filefolder containing the actionsproperties file (the node folder)
* _actionpropertiesfilename_ The filename of the actions property file


==== Methods

public final void registerFile(String filename, String fileext, Consumer<FileChangeType> callback) ::
Register an addition file to be observed.
This file is expected to be present (when existing) in the same folder as the
actions properties file:
* _filename_ The filename of the file to be observed
* _fileext_ The file extension of the file to be observed
* _callback_ The method to be called where a change is observed on this file

public void setBasicNodeActions(Action... basicnodeactions) :: define the set of
basic actions which are to be included in the Node's actions popup.

public void setNodeActions(Action... nodeactions) :: define the set of actions
which are particular to all projects of this node's project type.

public Action[] getAllNodeActions() :: Return an array of enabled actions for the node.
This includes the basicNodeActions, the NodeActions and any DynamicCLI actions
that were defined by the properties file.
 

==== Structure of the Properties file

The properties file must include a property _COMMANDCOUNT_ which indicates
the number of actions being defined in this file.

Each action being defined must have two or more property lines defined:

* _n.label_ the label displayed in the popup list (required)
* _n.command_ the CLI command to be executed when the action is selected (required)
* _n.inputfrom_ defines the source for the STDIN stream (optional):
** _file_ a file is to be used as the STDIN stream (see inputfile)
** _ui_ the Output window is to be the STDIN stream, providing keyboard input
** _noinput_ no input is provided for STDIN (default) 
* _n.inputfile_ defines the input file for STDIN (optional, unless _inputfrom_
is set to _file_)
* _n.sidebaractions_ the list of actions to be added to the Output window
sidebar (optional).
The actions will be separated by commas.
The actions available are:
** _cancel_ which kills the command being run (equivalent to Ctrl/C in a
CLI situation)
** _close_ closes the STDIN stream being sent to the command from the Output
window

note that _n_ must be an integer between 1 and _COMMANDCOUNT_.

[source]
----
1.label = Bake
1.command = jbake -b"
2.label = Copy NBPCG User Guide (html format)
2.command = bash -c "./copynbpcguguide ${NODEPATH} ~/DocumentationProjects/NBPCGDocumentation/UserGuide"
COMMANDCOUNT = 2
----

=== DynamicAction

Dynamic Action is the basic class of the Actions Support Plugin.
A Dynamic Action is an implementation of the Netbeans AbstractAction class.

A Dynamic Action is an Action which can be enabled or disabled, it is not
displayed when disabled.

The Action is enabled when an onAction method is defined.

==== Constructor

public DynamicAction() :: Construct a DynamicAction which is disabled.
       
==== Methods

public DynamicAction label(String label) :: Set the label for this Action:
* _label_ the label displayed when this DynamicAction is displayed.


public DynamicAction onAction(Runnable action) :: Set the Action method.
* _action_ the method to be run when this action is selected.       

public DynamicAction icon(ImageIcon icon) :: Set the Icon for this Action.
* _icon_ the icon to be displayed (the alternative to using a label).

=== DynamicCLIAction

DynamicCLIAction is a extension of DynamicAction.  It's action method
is a CLI command which will be executed.

A DynamicCLIAction is associated with a folder. This is the node folder
to which the action is attached.
This folder is set as the working directory when the command is executed.
When processing the CLI command it supports limited parameter substitution:

* ${NODEPATH} - is replaced with the node folder path.

Commands have to be parsed into CLI "phrases", such as options, option
parameters, filenames etc.
As this plugin can never have a full understanding of every command's syntax, it
employs a basic parsing technique (breaking on word breaks ie white space).
This works in the vast majority of cases, but there are times where the CLI "phrase"
should include multiple words. 
In this case, the phrase should be written with enclosing double quotes.
These quotes will be stripped from the generated command prior to it being
passed to ProcessBuilder.

The enableIf method is used to dynamically enable/disable a DynamicCLIAction
action.  This uses the enableIf function which is defined in the CLICommand.

A DynamicCLIActions has an Output window tab associated with it.  STDOUT and STDERR
output from the command excution will be presented here, and optionally STDIN 
lines can be entered in the window.
It is possible to add predefined actions to a sidebar of the Output window.
These actions provide further methods of interacting with the command.

==== Constructor

public DynamicCLIAction(CLICommand cliCommand) :: Construct a DynamicCLIAction.
* _cliCommand_ contains the details for the Action. 
       
==== Methods

public DynamicCLIAction enableIf() :: Check if the
action should be enabled.

=== CLICommand

The CLI Command is a structure containing all the information necessary
to create a DynamicCLIAction.  It can be constructed programmatically
or more commonly it will be populated with information from the
associated properties file. 

==== Constructor

public CLICommand(FileObject dir, String label) :: Construct a
CLI command object.
* _dir_  The node folder
* _label_ The label displayed when its associated CLIAction is displayed.
     
==== Methods

public CLICommand setParent(DynamicCLIAction parent) :: Set the associated
Action.
        
public CLICommand cliCommandLine(String cliCommandLine) :: Set the 
CLI command line.
    
public CLICommand enableIf(Supplier<Boolean> enableExpression) :: Define the
enabled test for the associated action.

public CLICommand inputfromFile(FileObject inputfile) :: The command will
receive input from the defined file.

public CLICommand inputfromUI() :: The command will receive lines of text
entered by the user in the output window.

public CLICommand noinput() :: the command will not receive input from the user.

public CLICommand actions(Action[] actions) :: define the set of actions to
be inserted into the output window.

public void executeCommand() :: execute this CLICommand.
