== Utilising the ActionsSupport NBM

=== Using the Library in a Maven build

The NBM must be added as a dependency in your POM.  To ensure Maven can find
it in the GitHub Maven repository, you will have add the following in your POM:

[source,xml]
----
<repositories>
    <repository>
        <id>github</id>
        <url>https://maven.pkg.github.com/The-Retired-Programmer/NetBeansNBMs</url>
    </repository>
</repositories>
----

and then add a dependency in your POM

[source,xml]
----
    <dependency>
        <groupId>uk.theretiredprogrammer</groupId>
        <artifactId>actionssupport</artifactId>
        <version>{revnumber}</version>
    </dependency>
----

=== Installing the NBM into Netbeans

To be able to use the Plugin it must be downloaded and then installed in Netbeans.

There is two ways to download the NBM:

* Releases of this product are stored in a Maven repository on GitHub.
It is possible to download an NBM from the Package available.

* However assuming you have added the dependency to you POM and have compiled your
code, a copy of the NBM will have been down loaded to your local Maven
repository (by default ~/.m2).

Once you have a downloaded copy on your machine, you follow the standard
Netbeans process to install the downloaded file (Tools>Plugins)

=== Links

* Releases are stored in a Packages Maven repository on 
https://github.com/The-Retired-Programmer/NetBeansNBMs/packages/1609349[GitHub]

* Source Code is stored in a Git repository on
https://github.com/The-Retired-Programmer/NetBeansNBMs[GitHub] as part of
a monorepro containing NBMs.

* Documentation (included JavaDoc API documentation) can be found on the
https://www.theretiredprogrammer.com/tags/ActionsSupport.html[TRP website].

* Documentation source is stored in a Git repository on
https://github.com/The-Retired-Programmer/ProductDocumentation[GitHub] as part of
a monorepro containing documentation.

* Development Process Guide for The-Retired-Programmer products can be found on the
https://www.theretiredprogrammer.com/tags/DevelopProcesses.html[TRP website].
