== ActionsSupport by Example

=== NodeActions

NodeActions creation:

* accepts the filename of a properties file
* enables the creation of DynamicAsyncActions from the information in a
properties file
* monitors the properties file for changes and refreshes the actions as
necessary
* enables support for assembling a node's actions

In the node constructor, add:

[source,java]
[%unbreakable]
----

XXXXProject(FileObject dir, ProjectState state) {
    .....
    nodeactions = new NodeActions(dir, "projectactions"); <1>
}

----
<1> create a NodeActions object, which will observe a
file _projectactions.properties_ within folder _dir_ for changes.
It will use the content of that file to define DynamicAsyncActions,
updating these actions whenever the file changes.

In order to be able to create the node's actions, NodeActions must be
made aware of all other actions required.
It will create the list containing three sections, with separators.   
Any of the sections may be empty.

The sections are:

* Basic node actions, typically the standard NetBeans actions which a node
would want to include
* Node actions, typically DynamicAsyncActions which are node type specific (ie
not defined in the node's properties file)
* DynamicAsyncActions which are created using the node's property file

The third group are created by the NodeActions constructor, while the
others must be passed to NodeActions (using setNodeBasicActions
and setNodeActions methods).

[source,java]
[%unbreakable]
----

    nodeactions.setNodeBasicActions(
            CommonProjectActions.renameProjectAction(),
            CommonProjectActions.copyProjectAction(),
            CommonProjectActions.closeProjectAction()  <1>
    );
    nodeactions.setNodeActions(
            new DynamicAsyncAction("Bake")
                    .onAction(() -> new NbCliDescriptor(projectDir, "jbake", "-b")
                    .stderrToIO()
                    .stdoutToIO()
                    .ioTabName("Bake " + projectDir.getName())
                    .exec("Baking"))  <2>
    );
----
<1> define 3 actions, in this case standard Netbeans Project Actions.
<2> define 1 DynamicAsyncAction, which will appear in all projects of this type.

The Node should use the NodeActions getAllNodeActions method to obtain
it's Action array.
This will combine all valid actions which have been made known to NodeActions.

[source, java]
[%unbreakable]
----

public Action[] getActions(boolean arg0) {
    return nodeactions.getAllNodeActions(); <1>
}

----
<1> Call NodeActions getAllNodeActions method to get a merged list of
all actions.

=== NbCliDescriptor

The NbCliDescriptor uses a set of Builder style methods to create the
description. Once the description is complete the external process can be started
and run to completion.

[source, java]
[%unbreakable]
----

NbCliDescriptor descriptor = new NbCliDescriptor(projectDir, "jbake", "-b") <1>
                        .ioTabName("Bake " + projectDir.getName()) <2>
                        .stderrToIO() <3>
                        .stdoutToIO() <3>
                        .exec("Baking")) <4>

----
<1> initialise the CLI command and arguements, and the required
working directory
<2> Request an IOTab, defining the tab label
<3> attach an external process stream to the IOTab
<4> once configuration is complete, 
the exec method is used to open or reuse an IOTab, start
the external process, connect all the required IO, run to process completion and
finally tidy up the resources used.

=== SaveBeforeAction

SaveBeforeAction is a helper class to support SaveIfModified for documents
which are open and modified.

There are two Use Cases:

**Documents are not in a Project**

In this case there is a simple method that is always enabled which can be
called prior to calling the NbCliDescriptor __.exec( ... )__ method.

[source, java]
[%unbreakable]
----

    SaveBeforeAction.saveIfModified(dataObject); <1>

----
<1> static method, does not need an instance of SaveBeforeAction as it does
not have a project property to set the mode.
SaveIfModified is always enabled.

This will ensure the document will be saved if it is in a modified state.
Only files modified by NetBeans will be considered as save candidates.

**Document are part of a Project**

In this case there is a need to parse the project properties file in order to
extract the mode.
This method will create an instance of SaveBeforeAction.
Additionally the project source root folder needs to be defined.

[source, java]
[%unbreakable]
----

    savebeforeaction = new SaveBeforeAction(properties, "save_before_publishing", ALL); <1>
    savebeforeaction.setSourceRoot(projectdir.getFileObject("src")); <2>

----
<1> create the SaveBeforeAction, parsing the properties. Parameter are:
* the properties for extracting the required property
* the required property key
* the default mode (as this property is optional)
<2> set the project source root folder (used with the ALL option)

Parsing the project's properties file will extract the mode, which
can be one of NO, YES or ALL.

The mode controls how any modified files are saved.
Only files modified by Netbeans will be considered as save candidates.

The possible values for the property are:

* NO - No modified file(s) are saved.

* YES - Only the file selected (see saveIfModifiedByMode(dataObject) below).

* ALL - All modified files that are within the source folder will be saved. 

Whenever a change to the properties file is observed, the project properties
file will need to be reparsed and a new instance of SaveBeforeAction created.
This occurs automatically as the project properties file is normally registered
with the NodeActions class.

[source, java]
[%unbreakable]
----

   nodeactionsmanager.registerFile("asciidoc", "properties", fct -> updateProperties(projectdir));

----

Finally there is a method to apply SaveIfModified to any project files
(controlled by mode).

[source, java]
[%unbreakable]
----

    aproject.getSaveBeforeAction().saveIfModifiedByMode(dataObject); <1>

----
<1> depending on the mode saves zero or more modified file(s).

Best practise will encapsulate these actions with the Project's Property
Handling class.  It then makes the SaveIfModified instance available to the project
instance, which can in turn make it available to any project code needing the
SaveIfModified functionality. 


=== DynamicAction and DynamicAsyncAction

While the primary use case will be the NodeActions
API, it is possible to use the DynamicAction classes independently.

==== DynamicAction examples

Add a DynamicAction to a node's actions.

[source,java]
[%unbreakable]
----

@Override
public Action[] getActions(boolean arg0) {
    return  new Action[]{
                ...
                null,
                new DynamicAction("do something")
                    .onAction(()->do_something()) <1> <2>
            });
}

----
<1> Create the DynamicAction
<2> ...and add it to the nodes's actions.
The action is enabled so needs no further initialisation.

==== DynamicAsyncAction example

Add a DynamicAsyncAction to a node's actions.

[source,java]
[%unbreakable]
----

@Override
public Action[] getActions(boolean arg0) {
    return  new Action[]{
                ...
                null,
                new DynamicAsyncAction("do something")
                    .onAction(()->do_something()) <1> <2>
            });
}

----
<1> Create the DynamicAsyncAction
<2> ...and add it to the nodes's actions.
The action is enabled so needs no further initialisation.
