== ActionsSupport by Example

=== NodeActions

NodeActions creation:

* accepts the filename of a properties file
* enables the creation of DynamicAsyncActions from the information in a
properties file
* monitors the properties file for changes and refreshes the actions as
necessary
* enables support for assembling a node's actions

In the node constructor, add:

[source,java]
[%unbreakable]
----

XXXXProject(FileObject dir, ProjectState state) {
    .....
    nodeactions = new NodeActions(dir, "projectactions"); <1>
}

----
<1> create a NodeActions object, which will observe a
file _projectactions.properties_ within folder _dir_ for changes.
It will use the content of that file to define DynamicAsyncActions,
updating these actions whenever the file changes.

In order to be able to create the node's actions, NodeActions must be
made aware of all other actions required.
It will create the list containing three sections, with separators.   
Any of the sections may be empty.

The sections are:

* Basic node actions, typically the standard NetBeans actions which a node
would want to include
* Node actions, typically DynamicAsyncActions which are node type specific (ie not
defined in the node's properties file)
* DynamicAsyncActions which are created using the node's property file

The third group are created by the NodeActions constructor, while the
others must be passed to NodeActions (using setNodeBasicActions
and setNodeActions methods).

[source,java]
[%unbreakable]
----

    nodeactions.setNodeBasicActions(
            CommonProjectActions.renameProjectAction(),
            CommonProjectActions.copyProjectAction(),
            CommonProjectActions.closeProjectAction()  <1>
    );
    nodeactions.setNodeActions(
            new DynamicAsyncAction("Bake")
                    .onAction(() -> new NbCliDescriptor(projectDir, "jbake", "-b")
                    .stderrToIO()
                    .stdoutToIO()
                    .ioTabName("Bake " + projectDir.getName())
                    .exec("Baking"))  <2>
    );
----
<1> define 3 actions, in this case standard Netbeans Project Actions.
<2> define 1 DynamicAsyncAction, which will appear in all projects of this type.

The Node should use the NodeActions getAllNodeActions method to obtain
it's Action array.
This will combine all valid actions which have been made known to NodeActions.

[source, java]
[%unbreakable]
----

public Action[] getActions(boolean arg0) {
    return nodeactions.getAllNodeActions(); <1>
}

----
<1> Call NodeActions getAllNodeActions method to get a merged list of
all actions.

=== NbCliDescriptor

The NbCliDescriptor uses a set of Builder style methods to create the
description. Once the description is complete the external process can be started
and run to completion.

[source, java]
[%unbreakable]
----

NbCliDescriptor descriptor = new NbCliDescriptor(projectDir, "jbake", "-b") <1>
                        .ioTabName("Bake " + projectDir.getName()) <2>
                        .stderrToIO() <3>
                        .stdoutToIO() <3>
                        .exec("Baking")) <4>

----
<1> initialise the CLI command and arguements, and the required
working directory
<2> Request an IOTab, defining the tab label
<3> attach an external process stream to the IOTab
<4> once configuration is complete, 
the exec method is used to open or reuse an IOTab, start
the external process, connect all the required IO, run to process completion and
finally tidy up the resources used.


=== DynamicAction and DynamicAsyncAction

While the primary use case will be the NodeActions
API, it is possible to use the DynamicAction classes independently.

==== DynamicAction examples

Add a DynamicAction to a node's actions.

[source,java]
[%unbreakable]
----

@Override
public Action[] getActions(boolean arg0) {
    return  new Action[]{
                ...
                null,
                new DynamicAction("do something")
                    .onAction(()->do_something()) <1> <2>
            });
}

----
<1> Create the DynamicAction
<2> ...and add it to the nodes's actions.
The action is enabled so needs no further initialisation.

==== DynamicAsyncAction example

Add a DynamicAsyncAction to a node's actions.

[source,java]
[%unbreakable]
----

@Override
public Action[] getActions(boolean arg0) {
    return  new Action[]{
                ...
                null,
                new DynamicAsyncAction("do something")
                    .onAction(()->do_something()) <1> <2>
            });
}

----
<1> Create the DynamicAsyncAction
<2> ...and add it to the nodes's actions.
The action is enabled so needs no further initialisation.
