== ActionsSupport in action

=== NodeActions example

NodeActions creation:

* accepts the filename of a properties file
* enables the creation of DynamicAyncActions from the information in a
properties file
* monitors the properties file for changes and refreshes the actions as
necessary
* enables support for assembling a node's actions

In the node constructor, add:

[source,java]
[%unbreakable]
----

XXXXProject(FileObject dir, ProjectState state) {
    .....
    dynamicactions = new NodeActions(dir, "projectactions"); <1>
}

----
<1> create a DynamicActions object, which will observe a
file _projectactions.properties_ within folder _dir_ for changes.
It will use the content of that file to define DynamicAsyncAction objects,
updating these actions whenever the file changes.

In order to be able to create the node's actions, NodeActions must be
made aware of all other actions required.
It will create the list containing three sections, with separators.   
Any of the sections may be empty.

The sections are:

* Basic node actions, typically the standard NetBeans actions which a node
would want to include
* Node actions, typically DynamicAsyncActions which are node type specific (ie not
defined in the node's properties file)
* DynamicAsyncActions which are created using the node's property file

The third group are defined by the NodeActions constructor, while the
others must be passed to NodeActions (using setNodeBasicActions
and setNodeActions methods).

[source,java]
[%unbreakable]
----

dynamicactions.setNodeBasicActions(
                CommonProjectActions.renameProjectAction(),
                CommonProjectActions.copyProjectAction(),
                CommonProjectActions.closeProjectAction() <1>
        );
dynamicactions.setNodeActions(
                new DynamicAsyncAction("Bake")
                        .onAction(
                            () -> new CLIExec(projectDir,"jbake -b")
                                    .stderrToOutputWindow()
                                    .stdoutToOutputWinow()
                                    .ioTabName("Bake " + projectDir.getName())
                                    .execute("Baking")) <2>
                );
        
----
<1> define 3 actions, in this case standard Netbeans Project Actions.
<2> define 1 DynamicAsyncAction, which will appear in all projects of this type.

The Node should use the NodeActions getAllNodeActions method to obtain
it's Action array.
This will combine all valid actions which have been made known to NodeActions.

[source, java]
[%unbreakable]
----

public Action[] getActions(boolean arg0) {
    return dynamicactions.getAllNodeActions(); <1>
}

----
<1> Call NodeActions getAllNodeActions method to get a merged list of
all actions.


=== Use of the DynamicAction/DynamicAsyncAction classes

While the majority of uses of this module will be via the NodeActions
API, it is possible to use the DynamicAction classes independently.

==== DynamicAction examples

Add a DynamicAction to a node's actions.

[source,java]
[%unbreakable]
----

@Override
public Action[] getActions(boolean arg0) {
    return  new Action[]{
                ...
                null,
                new DynamicAction("do something")
                    .onAction(()->do_something()) <1> <2>
            });
}

----
<1> Create the DynamicAction
<2> ...and add it to the nodes's actions.
The action is enabled so needs no further initialisation.

==== DynamicAsyncAction example

Add a DynamicAsyncAction to a node's actions.

[source,java]
[%unbreakable]
----

@Override
public Action[] getActions(boolean arg0) {
    return  new Action[]{
                ...
                null,
                new DynamicAsyncAction("do something")
                    .onAction(()->do_something()) <1> <2>
            });
}

----
<1> Create the DynamicAsyncAction
<2> ...and add it to the nodes's actions.
The action is enabled so needs no further initialisation.
