== Using the JBake NBM

=== Adding the NBM to NetBeans

To be able to use the Plugin it must be downloaded and then installed in NetBeans.

Releases of this product are stored in a Maven repository on GitHub.
It is possible to download an NBM from Packages.

Once you have a downloaded copy on your machine, you follow the standard
NetBeans process to install the downloaded file (Tools>Plugins)

The https://www.theretiredprogrammer.uk/tags/Actions%20Support.html[ActionsSupport NBM]
must be installed with or prior to installing this NBM.

=== Useful Links

* Releases are stored in a Packages Maven repository on 
https://github.com/The-Retired-Programmer/NetBeansNBMs/packages/1652862[GitHub]

* Source Code is stored in a Git repository on
https://github.com/The-Retired-Programmer/NetBeansNBMs[GitHub] as part of
a monorepro containing NBMs.

* Documentation can be found on the
https://www.theretiredprogrammer.uk/tags/JBake.html[TRP website].

* Documentation source is stored in a Git repository on
https://github.com/The-Retired-Programmer/ProductDocumentation[GitHub] as part of
a monorepro containing documentation.

* Development Process Guide for The-Retired-Programmer products can be found on the
https://www.theretiredprogrammer.uk/tags/DevelopProcesses.html[TRP website].
