== Utilising the AsciiDoc NBM

=== Installing the NBM

To be able to use the Plugin it must be downloaded and then installed in Netbeans.

Releases of this product are stored in a Maven repository on GitHub.
The NBM can be downloaded from the Package available.

Once you have a downloaded copy on your machine, you follow the standard
Netbeans process to install the downloaded file (Tools>Plugins).
The https://www.theretiredprogrammer.uk/tags/Actions%20Support.html[ActionsSupport NBM]
must also be installed with or prior to installing this NBM.

=== Links

* Releases are stored in a Packages Maven repository on 
https://github.com/The-Retired-Programmer/NetBeansNBMs/packages/1625417[GitHub]

* Source Code is stored in a Git repository on
https://github.com/The-Retired-Programmer/NetBeansNBMs[GitHub] as part of
a monorepro containing NBMs.

* Documentation can be found on the
https://www.theretiredprogrammer.uk/tags/AsciiDoc.html[TRP website].

* Documentation source is stored in a Git repository on
https://github.com/The-Retired-Programmer/ProductDocumentation[GitHub] as part of
a monorepro containing documentation.

* Development Process Guide for The-Retired-Programmer products can be found on the
https://www.theretiredprogrammer.uk/tags/DevelopProcesses.html[TRP website].
