== Availability

ActionsSupport files are available on GitHub.

The GitHub repository for ActionsSupport is: https://github.com/The-Retired-Programmer/ActionsSupport

The project uses the GitHub Releases to record the formal releases.  In addition
the NBM file created as part of the release in stored with the release information.

For a fuller description of The-Retired_Programmer use of GitHub as repository,
please look at: https://www.the-retired-programmer.uk/githubdevelopmentnotes.html

=== Including ActionsSupport in the project build 

The latest release NBM file can be downloaded from GitHub and place in the users
local copy of the Maven repository.
Add the following dependency in the projects POM to access the module
to be able to build the project.
[source,xml]
----

<dependencies>
    ...
    <dependency>
        <groupId>uk.theretiredprogrammer</groupId>
        <artifactId>actionssupport</artifactId>
        <version>1.2.0</version> <1>
    </dependency>
    ....
</dependencies>

----
<1> change the version to that of the latest version

=== Debugging/Testing a project which uses the ActionsSupport NBM

Ensure that the testing version of NetBeans being used has ActionsSupport
installed.
Use the NetBeans Tools>Plugins menu item to complete this action.
For more information about installing a NBM, please look at:
https://www.the-retired-programmer.uk/netbeansinstallingnbm.html

=== Installing the Project NBM

Once the project NBM has been built and tested, it can be installed into
any copies of Netbeans, as required.
Use the NetBeans Tools>Plugins menu item to complete this action.
Note that that the latest version of ActionsSupport must be installed prior
to installing any plug-in which uses ActionsSupport features.
For more information about installing a NBM, please look at:
https://www.the-retired-programmer.uk/netbeansinstallingnbm.html
