== ActionsSupport in action

=== NodeDynamicActions example

NodeDynamicActions creation:

* accepts the filename of a properties file
* enables the creation of DynamicCLIActions from the information in the
properties file
* monitors the properties file for changes and refreshes the actions as
necessary
* enables support for assembling a node's actions

In the node constructor, add:

[source,java]
----

XXXXProject(FileObject dir, ProjectState state) {
        .....
        dynamicactions = new NodeDynamicActions(dir, "projectactions"); <1>
    }

----
<1> create a DynamicActions object, which will observe a
file _projectactions.properties_ within folder _dir_ for changes.
It will use the content of that file to define DynamicCLIAction objects,
updating these actions whenever the file changes.

In order to be able to create the node's actions, NodeDynamicActions must be
made aware of all actions required.
It will create the list containing three sections, with separators.   
Any of the sections may be empty.

The sections are:

* Basic node actions, typically the standard NetBeans actions which a node
would want to include
* Node actions, typically DynamicCLIActions which are node type specific (ie not
defined in the node's properties file)
* DynamicCLIActions which are created using the node's property file

The third group is defined by the NodeDynamicActions constructor, while the
others must be passed to NodeDynamicActions (using setNodeBasicActions
and setNodeActions methods).

[source,java]
----

        dynamicactions.setNodeBasicActions(
                        CommonProjectActions.renameProjectAction(),
                        CommonProjectActions.copyProjectAction(),
                        CommonProjectActions.closeProjectAction() <1>
                );
        dynamicactions.setNodeActions(
                        new DynamicCLIAction(
                            new CLICommand(projectDir, "Bake")
                                .cliCommandLine("jbake -b") <2>
                        )
                );
        
----
<1> define 3 actions, in this case standard Netbeans Project Actions.
<2> define 1 DynamicCLIAction, which will appear in all projects of this type.



The Node should use the NodeDynamicActions getAllNodeActions method to obtain
it's Action array.  This will combine
all valid actions which have been made known to NodeDynamicActions.

[source, java]
----

public Action[] getActions(boolean arg0) {
    return dynamicactions.getAllNodeActions(); <1>
}

----
<1> Call NodeDynamicActions getAllActions method to get a merged list of
all actions.


=== Use of the DynamicAction/DynamicCLIAction classes independently

While the majority of uses of this module will be via the NodeDynamicActions
API, it is possible to use the DynamicAction classes independently.

==== DynamicAction examples

Add a DynamicAction to a node's actions.

[source,java]
----

@Override
public Action[] getActions(boolean arg0) {
    return  new Action[]{
                ...
                null,
                new DynamicAction()
                    .label("do something")
                    .onAction(()->do_something()) <1> <2>
            });
}

----
<1> Create the DynamicAction
<2> ...and add it to the nodes's actions.
The action is enabled so needs no further initialisation.

Add a Dynamic action as an icon in toolbar.

[source,java]
----

    DynamicAction toolbaraction = new DynamicAction()
                                    .icon("do_something_image.png")
                                    .onAction(()->do_something()) <1>
    ... <2>

----
<1> Create the DynamicAction
<2> ...and add it to the toolbar.

==== DynamicCLIAction example

Add a DynamicCLIAction to a node's actions.

[source,java]
----

@Override
public Action[] getActions(boolean arg0) {
    return  new Action[]{
                ...
                null,
                new DynamicCLIAction(
                        new CLICommand(projectDir, "Bake")
                            .cliCommandLine("jbake -b") <1>
                 ) <2>
            });
}

----
<1> create the CLICommand object and pass to DynamicCLIAction.
<2> Add the DynamicCLIAction to the nodes's actions.
The action is enabled so needs no further initialisation.
