== Introduction

The ActionsSupport NBM is a set of classes which can be used by other NetBeans
plugins, to allow the creation of Actions, with the ability to run external
programs.

This document is designed for developers of NetBeans Modules who wish to
integrate these features into their code.

These Action can execute:

* NetBeans methods
* Methods coded within the plugin
* External programs which can be executed in a CLI-like manner, allowing the use
of such programs from the NetBeans UI

=== DynamicActions and DynamicCLIActions

A Dynamic Action is an Action which
can be enabled or disabled and is not displayed when disabled.

These are two classes of Dynamic Actions:

* The base class (DynamicAction) which mirrors the Action class.
* The DynamicCLIAction class which provides the extended functionality to run
an external program.

DynamicActions can be associated with a particular node, either being for: 

* All projects of a particular type
* A specific project, as defined by a properties file
(DynamicCLIActions only).
  
=== NodeDynamicActions

NodeDynamicActions supports the creation of DynamicCLIActions for a 
node, by enabling the creation of DynamicCLIActions using a properties file.

NodeDynamicActions observes the node folder containing the property file,
ensuring the actions are updated whenever changes to the properties file occur.

Additional files within the node folder can be observed,
so that changes can trigger updates to any associated objects.

NodeDynamicActions provides a method for assembling node actions, combining
various sources of actions to create the final dynamic actions array required by
a node definition.
